apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  # Specify a name
  name: capmox-creds
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./capmox-creds.enc.yaml
