apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clu-01-nodes.yaml
  - cilium-crs
patches:
  - path: register-argo-patch.yaml
    target:
      kind: Job
      name: argocd-cluster-register
