apiVersion: batch/v1
kind: Job
metadata:
  name: argocd-cluster-register
  # unfortunately name isnt changed cuz this dont work with this patch
spec:
  template:
    spec:
      containers:
        - name: register
          env:
            # Adjust these if your CAPI cluster/namespace differ.
            - name: CHILD_CLUSTER_NAME
              value: phonkd-test-01
