repos:
  - repo: local
    hooks:
      - id: render-cilium-crs
        name: Render ClusterResourceSets
        entry: ./scripts/render-cilium-crs.sh
        language: script
        files: ^modules/spawner/sel-001/clusters/[^/]+/[^/]+/
        pass_filenames: false
