apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cilium-crs.yaml
  - ../../platform/

generators:
  - cilium-generator.yaml
helmCharts:
  - name: argo-cd
    releaseName: argocd
    namespace: argocd
    repo: https://argoproj.github.io/argo-helm
    version: 9.1.3
    valuesFile: ../../../k8s/argocd-child/argocd-values.yaml
    additionalValuesFiles:
      - argocd-extra-values.yaml
