nameReference:
- kind: Cluster
  fieldSpecs:
  - path: spec/clusterName
    kind: MachineDeployment
  - path: spec/template/spec/clusterName
    kind: MachineDeployment
- kind: ProxmoxCluster
  fieldSpecs:
  - path: spec/infrastructureRef/name
    kind: Cluster
- kind: TalosControlPlane
  fieldSpecs:
  - path: spec/controlPlaneRef/name
    kind: Cluster
- kind: TalosConfigTemplate
  fieldSpecs:
  - path: spec/template/spec/bootstrap/configRef/name
    kind: MachineDeployment
- kind: ProxmoxMachineTemplate
  fieldSpecs:
  - path: spec/template/spec/infrastructureRef/name
    kind: MachineDeployment
  - path: spec/infrastructureTemplate/name
    kind: TalosControlPlane
