apiVersion: v1
kind: Secret
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
stringData:
  config.yaml: ENC[AES256_GCM,data:IQNrYZzLHruCrcK/cJo8npieWTb/MkIecbKyb7jGOw6lAPVbKbqGQPo80Kn/6MD4E9nMOpTK3GiQuqVAyV47o/yfuIbUj/sFBS4LGZdEKUVyg+f5XIB37WV4KSyt/Fb5jFMk3zfrVFmioElRGN4Q9z2I5ZNJagjl641tbJp0+6w5Qy64J59MufGx7qNhMfB77szP2At5ECpXqRGRrLU7fkqthVsmes4RkQvHIbmvdOnWtZV0j4WydtiGSrXKqZH6b6bZ,iv:uobCrfDkJJsUpHXjY0TkvbVrOnkZi54vyMuryVeCuaw=,tag:RfawxTPbJ2HNuS3TmJxiew==,type:str]
sops:
  age:
    - recipient: age1jsnygd7gl62hzt06khdqkkjwa66v3snttmkep4wa5kl33luelfksdzytc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcjE3QUxGeXVWNWh6UVM0
        RWFKU3pQc08reURaWEo3ai9hcWN0UmhvK1UwClJ6QU5vc0tTUUtHZ1RBNUNzcCti
        b3NobGFRWHFVa1VTTGRpTmpva2dVRjAKLS0tIEpnK0t4UCtoL3I4dGJzbmZyODJY
        UWg1MDVJdGxCcG1OU3BKYkt2M1hvdEEKlPm1WVcHxJynWfm+/Gn9jkgbNlOiwSmN
        IYidwzjwnx3OBceU6hpi/iKYusCVbeGs77gqVvKrZhkIR7QVInMvZA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-27T12:07:28Z"
  mac: ENC[AES256_GCM,data:OztImRxD+a95p5WVyqCq0OP+3OSOUW0Hk6FbBKkuut7w57bXfn4tOxCnPflKk0Np0foKLqL0FV8uAyCZ9KhqOroqBDt+IbLUbdkiwEV756MU8wOxwzTAPW4N/y4HZfuFt/PKjDmqa6AUKOUKAjkMLykV4YDrlnGBuaRjZMUIuY8=,iv:Dx5zQz23lgwhvHuKlhf7yDOZwTFuaCEEZCSXPT5AvOw=,tag:6ekOFkoQMjXpVNiAnBq/Hg==,type:str]
  encrypted_regex: ^(config\.yaml)$
  version: 3.11.0
# config.yaml:
#         clusters:
#             # List of Proxmox clusters
#             - url: https://.../api2/json
#               # Skip the certificate verification, if needed
#               insecure: false
#               # Proxmox api token
#               token_id: kubernetes-csi@pve!csi
#               token_secret:
#               # Region name, which is cluster name
#               region: Region-1
