apiVersion: v1
stringData:
    config.yaml:
        clusters:
            # List of Proxmox clusters
            - url: https://oldblac.int.phonkd.net/api2/json
              # Skip the certificate verification, if needed
              insecure: false
              # Proxmox api token
              token_id: kubernetes-csi@pve!csi
              token_secret: ENC[AES256_GCM,data:O6u/DlgZJnFsQJ3VnMWmRG2cWnzC3yvmtwma+gemL2mHSMnK,iv:ov6CWNzkwwOtO1RLVIFlZ56NZ/HOdLINE/e++Pik9I8=,tag:QRg5THIu+86dy1s226VDfA==,type:str]
              # Region name, which is cluster name
              region: Region-1
kind: Secret
metadata:
    name: proxmox-csi-plugin
    namespace: csi-proxmox
sops:
    age:
        - recipient: age1jsnygd7gl62hzt06khdqkkjwa66v3snttmkep4wa5kl33luelfksdzytc6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUWtyaFExUVJ1K0pGTHVx
            MkdhU0IvUGQ3NVRab20vd0NGQW9RRi9DUmpZCnpOTlZmbUl0Nmh5TFI4M294SmVR
            WEJsWi9iVjdSN2pOOTZCY2dxVm5vakEKLS0tIE9UT0p2SVU5czVJWnAwVUR4dHdm
            bHRZZmZIc0UzYlFrTENaSFdnZlFodk0KbqcVfKlMAU1NXcfP/TNmZECUgQQH/sol
            1IKnj1vm2jRSiWhpXQjDQh9Y2GDSNhrsUNtZxbXUO5Mg7p8gpQhJBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T12:00:35Z"
    mac: ENC[AES256_GCM,data:7avQM0mc+ddu+6K2fdovi7GcXmFco0+u3D0ILFxMe9hO0N4pB9Ue05ikwIiswQ+FbKRbkO9y1hi1vZBOc7AhhFq6URIDGwd84GyT39nUSMsykljpVVLiTf+QIpKwY3AVvjYux4axsgE2Z47GQpxsz7RjSVwVuIzYAikiMp6HNNs=,iv:AVAM6Ca87dHWyTEcEppyQQt/QXADcXJ64QBP68xnHXI=,tag:pgoUKi3MfchoHghMkDotAg==,type:str]
    encrypted_regex: ^(token_secret)$
    version: 3.11.0
