apiVersion: v1
data:
    config.yaml: IyBjb25maWcueWFtbApjbHVzdGVyczoKICAjIExpc3Qgb2YgUHJveG1veCBjbHVzdGVycwoKICAtIHVybDogaHR0cHM6Ly9vbGRibGFjLmludC5waG9ua2QubmV0L2FwaTIvanNvbgogICAgIyBTa2lwIHRoZSBjZXJ0aWZpY2F0ZSB2ZXJpZmljYXRpb24sIGlmIG5lZWRlZAogICAgaW5zZWN1cmU6IGZhbHNlCiAgICAjIFByb3htb3ggYXBpIHRva2VuCiAgICB0b2tlbl9pZDogImt1YmVybmV0ZXMtY3NpQHB2ZSFjc2kiCiAgICB0b2tlbl9zZWNyZXQ6ICI4MDg2MDIxNC02ZDViLTQ2ZDktOGIxYi1lMzVmNmZjMjQ1YTAiCiAgICAjIFJlZ2lvbiBuYW1lLCB3aGljaCBpcyBjbHVzdGVyIG5hbWUKICAgIHJlZ2lvbjogUmVnaW9uLTEK
kind: Secret
metadata:
    name: proxmox-csi-plugin
    namespace: csi-proxmox
sops:
    age:
        - recipient: age1jsnygd7gl62hzt06khdqkkjwa66v3snttmkep4wa5kl33luelfksdzytc6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUWtyaFExUVJ1K0pGTHVx
            MkdhU0IvUGQ3NVRab20vd0NGQW9RRi9DUmpZCnpOTlZmbUl0Nmh5TFI4M294SmVR
            WEJsWi9iVjdSN2pOOTZCY2dxVm5vakEKLS0tIE9UT0p2SVU5czVJWnAwVUR4dHdm
            bHRZZmZIc0UzYlFrTENaSFdnZlFodk0KbqcVfKlMAU1NXcfP/TNmZECUgQQH/sol
            1IKnj1vm2jRSiWhpXQjDQh9Y2GDSNhrsUNtZxbXUO5Mg7p8gpQhJBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T23:15:18Z"
    mac: ENC[AES256_GCM,data:+j7kTuSFJS8o4AF2MJORU51C7r6M79zDZBAZAfxm+yyH673ZFir3QrqIHuweSaPHG7KBmQx8d3tfE0QhjVIgDRpfsQmrN7lHoeWt9OuRXtsFOYc2laU7juGNSZ1Ray+y9cQN1rSglgtxGSdhrhh+cpaBvpZlo3m20wjJ7g8GH1w=,iv:DgXpBXQATpHLLSqMCh4SYLm4Y9GQfzCxfWTU71FvFXE=,tag:Fj3SfWPnC+KuU+UWBOWQkw==,type:str]
    encrypted_regex: ^(token_secret)$
    version: 3.11.0
