apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 9.1.3
    releaseName: argocd
    namespace: argocd
    valuesFile: ../../../../../k8s/argocd-child/values.yaml
    additionalValuesFiles:
      - ./argo-values-clu01.yaml
