apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: capi2argo-cluster-operator
    repo: https://dntosas.github.io/capi2argo-cluster-operator/
    version: 1.5.0
    releaseName: capi2argo
    namespace: capi-system
