apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phonkd-dev
spec:
  destination:
    namespace: default
    server: https://192.168.1.226:6443
  source:
    path: k8s/clusters/phonkd-dev
    repoURL: https://github.com/phonkd/inventory
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    skipDryRunOnMissingResource: true
    timeout: 300
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true # without this argo's dry run will fail because the customresources cant be created since the customresourcedefinitions arent there yet (first providers which will create customresourcedefinitions must be created)
  retry:
    limit: 10
