apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://charts.longhorn.io
    name: longhorn
    version: 1.10.1
    valuesFile: ../../chlid/storage/longhorn/values.yaml
