apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clu-01-nodes.yaml
  - cilium-crs
  - ../../../../../../modules/k8s/register-argo-cluser/register-child-cluster-job.yaml
patches:
  - path: register-argo-patch.yaml
    target:
      kind: Job
      name: argocd-cluster-register
